version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - OPENROUTER_API_KEY=dummy-key   # dummy key for testing only
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "82:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
