name: Pre-Production Smoke Tests

on:
  push:
    branches:
      - preproduction   # only run on preproduction branch

jobs:
  preprod-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install test dependencies
        run: pip install pytest requests

      - name: Build Backend Docker Image
        run: docker build -t backend ./backend

      - name: Build Frontend Docker Image
        run: docker build -t frontend ./frontend

      - name: Run Backend Container
        run: docker run -d -p 5000:5000 --name backend backend

      - name: Run Frontend Container
        run: docker run -d -p 8080:80 --name frontend frontend

      - name: Wait for services
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5000/health && curl -s http://localhost:8080; then
              echo "Services are up!"
              exit 0
            fi
            echo "Waiting for services..."
            sleep 3
          done
          echo "Services failed to start"
          exit 1

      - name: Run Smoke Tests
        run: pytest -v tests/smoke/

      # Auto-merge into main only if tests pass
      - name: Merge preproduction into main
        if: success()
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: preproduction
          target_branch: main
          title: "Auto-merge preproduction → main"
          body: "Preprod tests passed, merging into main for deployment."
