name: Build and Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Trigger Deploy Workflow'
        required: true
        default: 'true'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # === Step 0: Skip if this run was triggered by the previous merge commit ===
      - name: Skip duplicate CI runs
        if: ${{ github.actor == 'github-actions[bot]' }}
        run: |
          echo "Skipping duplicate run triggered by GitHub Actions bot."
          exit 0

      # === Step 1: Checkout the main branch with full history ===
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0   # ✅ Fetch full commit history for merging
          token: ${{ secrets.GH_PAT }}  # Personal Access Token (Classic) with repo permissions

      # === Step 2: Fetch preproduction branch ===
      - name: Fetch preproduction branch
        run: |
          git fetch origin preproduction

      # === Step 3: Merge preproduction into main ===
      - name: Merge preproduction into main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git merge origin/preproduction --no-ff -m "Auto-merge preproduction → main [skip ci]"

      # === Step 4: Push merged changes back to GitHub ===
      - name: Push updated main branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} main

      # === Step 5: Configure AWS credentials ===
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # === Step 6: Login to ECR ===
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 \
            | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com

      # === Step 7: Build & push backend image ===
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t portfolio-backend ./backend
          docker tag portfolio-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/instancebackend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/instancebackend:latest

      # === Step 8: Build & push frontend image ===
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t portfolio-frontend ./frontend
          docker tag portfolio-frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/instancefrontend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/instancefrontend:latest

      # === Step 9: SSH into EC2 & deploy ===
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x ~/deploy.sh
            ~/deploy.sh

      # === Step 10: Verify frontend health ===
      - name: Verify Frontend is live
        run: |
          for i in {1..15}; do
            if curl -s --fail https://limjiajing.com > /dev/null; then
              echo "Frontend is live!"
              exit 0
            fi
            echo "Waiting for frontend..."
            sleep 5
          done
          echo "Frontend failed to come online!"
          exit 1

      # === Step 11: Verify backend health ===
      - name: Verify Backend is live
        run: |
          for i in {1..15}; do
            if curl -s --fail https://limjiajing.com/health > /dev/null; then
              echo "Backend is live!"
              exit 0
            fi
            echo "Waiting for backend..."
            sleep 5
          done
          echo "Backend failed to come online!"
          exit 1
        
      # === Step: Notify Discord with Embed ===
      - name: Notify Discord
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            COLOR=3066993  # green
            STATUS="✅ Deployment succeeded!"
          else
            COLOR=15158332 # red
            STATUS="❌ Deployment failed!"
          fi

          PAYLOAD=$(jq -n \
            --arg status "$STATUS" \
            --arg repo "${{ github.repository }}" \
            --arg branch "${{ github.ref_name }}" \
            --arg actor "${{ github.actor }}" \
            --arg run_id "${{ github.run_id }}" \
            --arg run_url "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --argjson color "$COLOR" \
            '{
              "embeds": [{
                "title": $status,
                "color": $color,
                "fields": [
                  {"name": "Repository", "value": $repo, "inline": true},
                  {"name": "Branch", "value": $branch, "inline": true},
                  {"name": "Triggered by", "value": $actor, "inline": true},
                  {"name": "Workflow Run", "value": $run_url, "inline": false}
                ],
                "footer": {"text": "GitHub Actions • Deploy Workflow"}
              }]
            }'
          )

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
